### PR TITLE
reimplentation of 404 in react

### PR DESCRIPTION
**Pull request by shoshta73**
lazy way -- dont ask only way I found that works

### CODE REVIEW

**Review by jasjs1 — APPROVED** [review]
Code looks good!

**Comment by shoshta73** [comment]
if you are ok with this i can offset MVP of flexnote by few day to do full react

**Comment by jasjs1** [comment]
If you want to @Shoshta73

**Comment by shoshta73** [comment]
ok keep this branch alive

**Comment by jasjs1** [comment]
@Shoshta73 👍🏻

**Pull request merged**
